### ISSUE TITLE
Do you have a less cluttered example?

### ISSUE THREAD

**Issue by martinthomson** [rfc-format/draft-iab-rfc-css-bis#9]
A real draft, for instance.  The clutter on the current one makes it hard to imagine what it might look like in practice.  It's great to test all the various combinations, but a real document would be better for getting stylistic feedback.

**Comment by hlflanagan** [comment]
Not right now, though I am hoping people will help me create a few over the next few weeks.

**Comment by martinthomson** [comment]
sample2 is nice, thanks
